version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: raw data from Greenweez
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Greenweez sales / one row per product_id per order_id
        columns:
          - name: orders_id
            description: order identifier
          - name: pdt_id
            description: product identifier
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"

      - name: product
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
          - name: products_id
            description: primary key of products
            tests:
              - unique
              - not_null
          - name: purchse_price
            description: purchase price of the product

      - name: ship
        identifier: raw_gz_ship
        description: shipping information for Greenweez orders
        columns:
          - name: orders_id
            description: primary key of orders shipping table
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: shipping fee
          - name: ship_cost
            description: shipping cost
          - name: logCost
            description: logistic cost